default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 5
  timeout: 5000
  username: 'mikkie'
  password: '12345678'

development:
  <<: *default
  database: db/development

production:
  <<: *default
  database: db/production
